### ISSUE TITLE
Error when using leftLabels/rightLabels

### ISSUE THREAD

**Issue by gbmd** [anazalea/pySankey#38]
https://github.com/anazalea/pySankey/blob/811a63823692b2ae3d346bbda4ea5990677f409c/pysankey/sankey.py#L42
pretty sure this should be len(labels) > 0...

```sankey(df_compare['pred_CNN'].values,
       df_compare['pred_RF'].values,
       colorDict=colorDict,
       figure_name='visualization/output/sankeytest',
       rightLabels=['C','I','R','P','AUX'])```

yields 

`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/georg/.local/share/virtualenvs/pvpotential-aZgESz7z/lib/python3.8/site-packages/pySankey/sankey.py", line 119, in sankey
    check_data_matches_labels(leftLabels, df['right'], 'right')
  File "/home/georg/.local/share/virtualenvs/pvpotential-aZgESz7z/lib/python3.8/site-packages/pySankey/sankey.py", line 34, in check_data_matches_labels
    if len(labels >0):
TypeError: '>' not supported between instances of 'str' and 'int'`

**Comment by Pierre-Sassoulas** [comment]
Duplicate of almost half of the issue in this repo #23

**Comment by endolith** [comment]
https://addons.mozilla.org/en-US/firefox/addon/lovely-forks/ :)

**Comment by Pierre-Sassoulas** [comment]
Nice addon @endolith ! Although it does not seem to work for fork of forks.

**Comment by auesro** [comment]
Just to help out others coming after this issue and related ones:

Installing pySankeyBeta works, the error regarding `len(labels) > 0` is fixed, the "problem" is:
`leftLabels` and `rightLabels` must be provided in a Bottom-Top order to the sankey function. 
For example: if you want A, B, C, D to be your left labels, appearing in that order from the top to the bottom of the figure, then `leftLabels = ['D','C','B','A']`

It is a small detail, but I did not find it mentioned anywhere. I just discovered it by chance.

Hope it helps others!

A
